### ISSUE TITLE
Home "Get started" button leads to sign-in page, not sign-up.

### ISSUE THREAD

**Issue by acmattson3** [FireAstrox/CaneBane-Board#7]
I was confused when the get started page led me to a page where I entered my information, only to be told my credentials are invalid. I suggest you make that button lead to the sign up page (maybe then add an "already a user?" prompt to the bottom of the sign-up page to prevent existing user confusion). Just a small suggestion, but it had me confused and disrupted the standard user flow.

**Comment by FireAstrox** [comment]
I forgot to mention this issue in my commit but the Flow should be a bit better now and takes people straight to signup with an option to log in
