### ISSUE TITLE
Board code copy to clipboard button does nothing.

### ISSUE THREAD

**Issue by acmattson3** [FireAstrox/CaneBane-Board#8]
![image](https://github.com/user-attachments/assets/8be308b9-534d-4903-a3bd-44ec61bd94bf)
When clicking the copy to clipboard button next to the board code, the code claims to copy to my clipboard but is not copied.

**Comment by FireAstrox** [comment]
The main issue is the API is not available/reached in the Live Build, I added a fix that should hopefully fix the button once its pushed into live

**Comment by FireAstrox** [comment]
This does work now in live production
